#!/usr/bin/env ruby

filename = ARGV[0]
data = File.read(filename)

components_changed = (
  data.scan(/selectors\/(.*?)\.yml/).map { |x| x[0] } +
  data.scan(/components\/(.*?)\.less/).map { |x| x[0] }
).uniq.sort

exit if components_changed.empty?

File.open(filename, 'w') do |io|
  io << "# [#{components_changed.join(', ')}] \n"
  io << data
end


